version: '3.7'

services:

  real_estate:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=user/__init__.py
      - FLASK_ENV=development
      - COMPOSE_CONVERT_WINDOWS_PATHS=1